# fly.toml app configuration file generated for routing-service on 2025-11-28T23:13:17-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'routing-service'
primary_region = 'iad'

[build]
  dockerfile = './Containerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 550
    soft_limit = 500

[[vm]]
  size = 'shared-cpu-1x'
