app = 'vehicles-service'
primary_region = 'iad'

[build]
  dockerfile = "./Containerfile"

# [[services]]
#   auto_stop_machines = false
#   auto_start_machines = false
#   min_machines_running = 1

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3000
min_machines_running = 0
processes = [ "app" ]

  [http_service.concurrency]
  hard_limit = 550
  soft_limit = 500
  type = "requests"


[[vm]]
  size = 'shared-cpu-1x'
