name: "Fly Deploy: vehicles-service"
on:
  push:
    branches:
      - release/main  # for deployments of the entire application
      - release/vehicles  # for deployments of just the gbfs service

jobs:
  deploy:
    name: Deploy vehicles-service
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c ./services/vehicles/fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.VEHICLES_SERVICE_FLY_API_TOKEN }}