name: "Fly Deploy: gbfs-service"
on:
  push:
    branches:
      - release/main  # for deployments of the entire application
      - release/gbfs  # for deployments of just the gbfs service
      - feat/init
jobs:
  deploy:
    name: Deploy gbfs-service
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c ./services/gbfs/fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.GBFS_SERVICE_FLY_API_TOKEN }}